import type { AuthStore } from "../src/auth/store";

export function testStore(overrides: Partial<AuthStore> = {}): AuthStore {
  return {
    database: {} as AuthStore["database"],
    sync: {
      isAvailable: () => Promise.resolve(false),
      withIdentity: () => Promise.reject(new Error("sync unavailable in this test")),
      claimStorageDeletes: () => Promise.resolve([]),
      enqueueStorageDelete: () => Promise.resolve(),
      completeStorageDelete: () => Promise.resolve(),
      failStorageDelete: () => Promise.resolve(),
    },
    ensureIdentityUser: () => Promise.resolve(true),
    seedDahliaClient: () => Promise.resolve(),
    listDahliaSessions: () => Promise.resolve([]),
    revokeDahliaSession: () => Promise.resolve(false),
    listModelAliases: () => Promise.resolve([]),
    getEnabledModelAlias: () => Promise.resolve(null),
    createModelAlias: () => Promise.resolve(false),
    updateModelAlias: () => Promise.resolve(false),
    deleteModelAlias: () => Promise.resolve(false),
    listAdminUsers: () => Promise.resolve([]),
    isAdminUser: () => Promise.resolve(false),
    addAdminUser: () => Promise.resolve(null),
    removeAdminUser: () => Promise.resolve("not_found"),
    getExternalOrganization: () => Promise.resolve(null),
    listExternalOrganizationMembers: () => Promise.resolve(null),
    listExternalTeams: () => Promise.resolve(null),
    createExternalTeam: () => Promise.resolve(null),
    updateExternalTeam: () => Promise.resolve(null),
    deleteExternalTeam: () => Promise.resolve(false),
    listExternalTeamMembers: () => Promise.resolve(null),
    addExternalTeamMember: () => Promise.resolve(false),
    removeExternalTeamMember: () => Promise.resolve(false),
    listArtifacts: () => Promise.resolve([]),
    getArtifact: () => Promise.resolve(null),
    createArtifact: () => Promise.resolve(null),
    commitArtifactStorage: () => Promise.resolve(null),
    updateArtifactVisibility: () => Promise.resolve(null),
    deleteArtifact: () => Promise.resolve(false),
    deleteVaultPermissionsForPrincipal: () => Promise.resolve(),
    deleteVaultPermissionsForOrganization: () => Promise.resolve(),
    ...overrides,
  };
}
