import { Select } from "./Select";
import { useEffect } from "react";
import { RequestError, uiText } from "./api";
import { useLiveJSON, useLivePage } from "./live-data";
import { parseSummary, SummaryContent } from "./MeetingContent";
import { summaryMetadata, type SummaryVersion } from "../summary/metadata";

export interface LatestSummary {
  version: number;
  revision: number;
  present: boolean;
  record?: { title: string | null; document: string | null; createdAt: string | null };
}
type Version = Omit<SummaryVersion, "createdAt" | "savedAt"> & { createdAt: string | null; savedAt: string };

export function SummaryHistory({ base, latest, selected, onSelect }: {
  base: string; latest?: LatestSummary; selected: number | null; onSelect: (version: number | null) => void;
}) {
  const versions = useLivePage<Omit<Version, "document">>(`${base}/summary`);
  const history = useLiveJSON<Version>(selected === null ? undefined : `${base}/summary/${selected}`);
  useEffect(() => {
    if (history.error instanceof RequestError && history.error.status === 404) onSelect(null);
  }, [history.error, onSelect]);
  const summary = selected === null ? latest?.record : history.data;
  const raw = summary?.document;
  const title = summary?.title;
  const metadata = raw ? summaryMetadata(raw) : null;
  const error = versions.error ?? history.error;
  const inputLabels: Record<string, string> = { transcript: uiText("Transcript", "文字起こし"), image: uiText("Images", "画像"),
    audio: uiText("Audio", "音声"), note: uiText("Notes", "メモ"), context: uiText("Meeting context", "会議情報") };
  const detailLabels: Record<string, string> = { concise: uiText("Concise", "簡潔"), standard: uiText("Standard", "標準"),
    detailed: uiText("Detailed", "詳細"), eventSession: uiText("Event session", "イベントセッション") };
  return <>
    <div className="history-toolbar">
      <label>{uiText("Version", "バージョン")} <Select value={selected ?? "latest"}
        onValueChange={(value) => onSelect(value === "latest" ? null : Number(value))}>
        <option value="latest">{uiText("Current", "現在")}{latest && ` (v${latest.version})`}</option>
        {selected !== null && !versions.data?.items.some((version) => version.version === selected) && <option value={selected}>v{selected}</option>}
        {versions.data?.items.map((version) => {
          const model = version.metadata?.response?.model ?? version.metadata?.request.model;
          return <option key={version.version} value={version.version}>
            v{version.version} · {new Date(version.savedAt).toLocaleString()}{model && ` · ${model}`}
          </option>;
        })}
      </Select></label>
      {versions.data?.nextCursor && <button className="secondary" disabled={versions.loadingMore} onClick={versions.loadMore}>{uiText("Load older versions", "以前の版を読み込む")}</button>}
      {selected !== null && <span>{uiText("Read-only version", "過去版（閲覧のみ）")}</span>}
    </div>
    {error && <p role="alert" className="error">{error.message} <button className="secondary" onClick={() => { versions.reload(); history.reload(); }}>{uiText("Retry", "再試行")}</button></p>}
    {selected !== null && history.loading && !history.data && <p role="status">{uiText("Loading…", "読み込み中…")}</p>}
    {raw ? <>
      {title && <h2 className="summary-title">{title}</h2>}
      {metadata && <details className="summary-generation-metadata">
        <summary>{uiText("Generation details", "生成情報")} · {metadata.response?.model ?? metadata.request.model ?? "—"} · {metadata.response?.reasoning?.effort ?? metadata.request.reasoning?.effort ?? "—"}</summary>
        <dl>
          <dt>{uiText("Generated by", "生成したシステム")}</dt><dd>{metadata.generatedBy === "server" ? uiText("Server", "サーバー") : "Local Codex"}</dd>
          <dt>{uiText("Inputs", "入力")}</dt><dd>{metadata.inputTypes.map((type) => inputLabels[type] ?? type).join(", ")}</dd>
          <dt>{uiText("Detail / language", "詳細度・言語")}</dt><dd>{metadata.detailLevel ? detailLabels[metadata.detailLevel] ?? metadata.detailLevel : "—"} / {metadata.outputLanguage ?? "—"}</dd>
        </dl>
        <dl>
          <dt>{uiText("Requested model", "指定モデル")}</dt><dd>{metadata.request.model ?? "—"}</dd>
          <dt>{uiText("Response model", "応答モデル")}</dt><dd>{metadata.response?.model ?? "—"}</dd>
          <dt>{uiText("Requested / returned effort", "指定・応答の推論強度")}</dt><dd>{metadata.request.reasoning?.effort ?? "—"} / {metadata.response?.reasoning?.effort ?? "—"}</dd>
          <dt>{uiText("Input / output / total tokens", "入力・出力・合計トークン")}</dt><dd>{metadata.response?.usage?.input_tokens ?? "—"} / {metadata.response?.usage?.output_tokens ?? "—"} / {metadata.response?.usage?.total_tokens ?? "—"}</dd>
          <dt>{uiText("Cached / reasoning tokens", "キャッシュ・推論トークン")}</dt><dd>{metadata.response?.usage?.input_tokens_details?.cached_tokens ?? "—"} / {metadata.response?.usage?.output_tokens_details?.reasoning_tokens ?? "—"}</dd>
          {metadata.response?.id && <><dt>{uiText("Response ID", "応答 ID")}</dt><dd>{metadata.response.id}</dd></>}
          {metadata.response?.created_at != null && <><dt>{uiText("Response created", "応答作成日時")}</dt><dd>{new Date(metadata.response.created_at * 1000).toLocaleString()}</dd></>}
        </dl>
      </details>}
      <SummaryContent document={parseSummary(raw)} />
    </> : (selected === null && latest) && <p className="content-empty">{uiText("No summary yet", "要約はまだありません")}</p>}
  </>;
}
