import { apiQuery, type ApiQuery } from "./live-data";
import type { components } from "./generated-api";
import { Select } from "./Select";
import { useRef, useState } from "react";
import { uiText } from "./api";
import { useLivePage, useLiveQuery } from "./live-data";
import { TranscriptTime } from "./MeetingContent";
import { Button } from "./components/ui/button";
type Version = components["schemas"]["Transcript"];
type Body = components["schemas"]["TranscriptContent"];

export async function readTranscriptPages(query: ApiQuery<Body>, minimum: number, signal: AbortSignal): Promise<Body> {
  const first = await query.load(signal);
  const result = { ...first, items: [...first.items ?? []] };
  while (result.nextCursor && result.items.length < minimum) {
    const page = await query.load(signal, result.nextCursor);
    if (page.version !== first.version || page.syncRevision !== first.syncRevision) {
      throw new Error(uiText("The transcript changed. Retry to load the current version.", "文字起こしが更新されました。再試行してください。"));
    }
    if (page.nextCursor === result.nextCursor || !page.items?.length) throw new Error("Invalid transcript page");
    result.items.push(...page.items ?? []);
    result.nextCursor = page.nextCursor;
  }
  return result;
}

export function TranscriptHistory({ meetingId, timeBase }: { meetingId: string; timeBase: string }) {
  const [selected, setSelected] = useState<number | null>(null);
  const demand = useRef(1);
  const versions = useLivePage<Version>(apiQuery("listTranscripts", { params: { path: { meetingId } } }));
  const contentQuery = selected === null ? apiQuery("getLatestTranscript", { params: { path: { meetingId } } })
    : apiQuery("getTranscript", { params: { path: { meetingId, version: String(selected) } } });
  const body = useLiveQuery<Body>(contentQuery.key, (signal, previous) =>
    readTranscriptPages(contentQuery, Math.max(demand.current, previous?.items?.length ?? 1), signal));
  const metadata = body.data?.transcript?.metadata;
  const error = versions.error ?? body.error;
  return <div>
    <div className="mb-5 flex flex-wrap items-center gap-3 text-xs text-muted-foreground">
      <label className="flex items-center gap-2">{uiText("Version", "バージョン")} <Select value={selected ?? "latest"} onValueChange={(value) => {
        demand.current = 1;
        setSelected(value === "latest" ? null : Number(value));
      }}>
        <option value="latest">{uiText("Current", "現在")}</option>
        {versions.data?.items.map((version) => <option key={version.id} value={version.version}>
          v{version.version} · {new Date(version.createdAt).toLocaleString()} · {version.metadata?.request.model ?? "—"}
        </option>)}
      </Select></label>
      {versions.data?.nextCursor && <Button variant="outline" size="sm" disabled={versions.loadingMore} onClick={versions.loadMore}>{uiText("Load older versions", "以前の版を読み込む")}</Button>}
      {selected !== null && <span>{uiText("Read-only version", "過去版（閲覧のみ）")}</span>}
    </div>
    {error && <p role="alert" className="text-sm text-destructive">{error.message} <Button variant="outline" size="sm" onClick={() => { versions.reload(); body.reload(); }}>{uiText("Retry", "再試行")}</Button></p>}
    {body.loading && !body.data && <p className="text-sm text-muted-foreground" role="status">{uiText("Loading…", "読み込み中…")}</p>}
    {metadata && <details className="mb-5 rounded-lg border bg-muted/30 p-3 text-xs text-muted-foreground [&_dl]:mt-3 [&_dl]:grid [&_dl]:grid-cols-[minmax(130px,auto)_1fr] [&_dl]:gap-x-4 [&_dl]:gap-y-1 [&_summary]:cursor-pointer">
      <summary className="text-foreground">{uiText("Generation details", "生成情報")} · {metadata.request.model}</summary>
      <dl><dt>{uiText("Provider / model", "プロバイダー・モデル")}</dt><dd>{metadata.provider} / {metadata.request.model}</dd></dl>
      {metadata.runs.map((run, index) => <dl key={index}>
        <dt>{uiText("Generated by", "生成したシステム")}</dt><dd>{run.generatedBy}</dd>
        <dt>{uiText("Language", "言語")}</dt><dd>{run.language?.mode ?? "—"} / {run.recognitionLocales?.join(", ") ?? run.language?.locales.join(", ") ?? "—"}</dd>
        <dt>{uiText("Completed", "完了日時")}</dt><dd>{run.completedAt ? new Date(run.completedAt).toLocaleString() : "—"}</dd>
        {run.response && <>
          <dt>{uiText("Response model", "応答モデル")}</dt><dd>{run.response.model ?? "—"}</dd>
          <dt>{uiText("Input / output / total tokens", "入力・出力・合計トークン")}</dt><dd>{run.response.usage?.input_tokens ?? "—"} / {run.response.usage?.output_tokens ?? "—"} / {run.response.usage?.total_tokens ?? "—"}</dd>
          {run.response.id && <><dt>{uiText("Response ID", "応答 ID")}</dt><dd>{run.response.id}</dd></>}
        </>}
      </dl>)}
    </details>}
    {body.data?.items?.length === 0 && <p className="my-9 text-center text-sm text-muted-foreground">{uiText("No transcript", "文字起こしはありません")}</p>}
    {body.data?.items?.map((segment) => <div className="grid grid-cols-[max-content_minmax(0,1fr)] gap-3 border-b border-border/50 py-1.5 max-sm:grid-cols-1 max-sm:gap-1" key={segment.segmentId}>
      <TranscriptTime startTime={segment.startedAt} timeBase={timeBase} />
      <p className="whitespace-pre-wrap text-xs leading-5">{segment.speakerLabel && <span className="mr-2 inline-block rounded bg-muted px-1.5 py-px text-[10px] leading-4 text-muted-foreground">{segment.speakerLabel}</span>}{segment.text}</p>
    </div>)}
    {body.data?.nextCursor && <Button variant="outline" size="sm" className="mt-4" disabled={body.loading} onClick={() => {
      demand.current = (body.data?.items?.length ?? 0) + 1;
      body.reload();
    }}>{uiText("Load more", "さらに表示")}</Button>}
  </div>;
}
