CREATE TABLE "modelAlias" (
  "alias" TEXT PRIMARY KEY NOT NULL,
  "upstreamModel" TEXT NOT NULL,
  "displayName" TEXT,
  "enabled" INTEGER NOT NULL DEFAULT 1,
  "createdAt" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "platformAdmin" (
  "email" TEXT PRIMARY KEY NOT NULL,
  "createdAt" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
