// pnpm dev:client -> /tests/browser/workspace-memory.html. Mocked HTTP only.
import { createRoot } from "react-dom/client";
import { SaveSharedMemory, WorkspaceMemory } from "../../src/client/WorkspaceMemory";
import "../../src/client/styles.css";
const preview = new URLSearchParams(location.search).has("preview");
Object.defineProperty(navigator, "language", { value: preview ? "ja-JP" : "en-US", configurable: true });
let status = { enabled: true, imagesEnabled: true, imagesAvailable: true, status: "error", errorCode: "upstream", skippedCount: 0, skippedSources: [] };
let notesFail = false;
let statusFail = false;
let writes = 0;
let purges = 0;
let sharedContent: string | undefined;
let notes = [{ id: "note", content: "Follow up on the migration plan next week.", revision: 1, updatedAt: "2026-09-29T00:00:00Z" }];
window.fetch = async (input, init) => {
  const request = new Request(new URL(input instanceof Request ? input.url : input, location.href), init);
  const path = new URL(request.url).pathname;
  if (path.endsWith("/analysis/status")) return statusFail ? Response.json({ error: "failed" }, { status: 503 }) : Response.json(status);
  if (path.endsWith("/analysis/settings")) { writes++; status = { ...status, ...await request.json(), status: "pending", errorCode: "" }; return Response.json(status); }
  if (path.endsWith("/notes") && request.method === "POST") { sharedContent = (await request.json<{ content: string }>()).content; return Response.json({}); }
  if (path.endsWith("/notes")) return notesFail ? Response.json({ error: "failed" }, { status: 503 }) : Response.json({ items: notes, nextCursor: null });
  if (request.method === "DELETE" && path.endsWith("/memory")) { purges++; notes = []; return Response.json({}); }
  throw new Error(`Unexpected request: ${path}`);
};
const root = createRoot(document.getElementById("root")!);
let enabledWorkspace = "";
const onEnabledWorkspace = (id: string) => { enabledWorkspace = id; };
const mount = (role = "admin", key = role, compact = false) => root.render(<div className="mx-auto max-w-3xl p-6"><WorkspaceMemory key={key} workspaceId="team" role={role} compact={compact} onEnabledWorkspace={onEnabledWorkspace} /></div>);
const assert: (value: unknown, message: string) => asserts value = (value, message) => { if (!value) throw new Error(message); };
const until = async (test: () => unknown) => { const end = performance.now() + 5000; while (!test()) { if (performance.now() > end) throw new Error("UI timed out"); await new Promise(requestAnimationFrame); } };
const button = (label: string) => [...document.querySelectorAll<HTMLButtonElement>("button")].find(b => b.textContent === label);
const switchFor = (suffix: string) => document.querySelector<HTMLButtonElement>(`[role="switch"][id$="-${suffix}"]`)!;
async function run() {
  mount();
  await until(() => switchFor("analysis") && !switchFor("analysis").disabled);
  if (preview) return;
  assert(document.querySelector('[role="alert"]') && button("Retry"), "Error recovery missing");
  assert(!document.querySelector("details")!.open, "Destructive section is expanded by default");
  switchFor("analysis").click();
  await until(() => document.querySelector("[data-confirm]"));
  assert(writes === 0 && switchFor("analysis").getAttribute("aria-checked") === "true", "Switch changed before confirmation");
  (document.querySelector("[data-confirm]") as HTMLButtonElement).click();
  await until(() => !document.querySelector('[role="dialog"]') && switchFor("analysis").getAttribute("aria-checked") === "false");
  assert(Number(writes) === 1 && !status.enabled, "Pause was not saved");
  notesFail = true; button("Show shared notes")!.click();
  await until(() => document.body.textContent?.includes("Could not load shared notes"));
  notesFail = false; button("Retry")!.click();
  await until(() => document.body.textContent?.includes(notes[0]!.content));
  assert(button("Edit") && button("Delete"), "Admin note actions missing");
  mount("viewer");
  await until(() => !document.querySelector('[role="switch"]'));
  button("Show shared notes")!.click();
  await until(() => document.body.textContent?.includes(notes[0]!.content));
  assert(!button("Edit") && !button("Delete") && !button("Erase memories"), "Viewer has write controls");
  notes = []; mount("editor");
  await until(() => button("Show shared notes")); button("Show shared notes")!.click();
  await until(() => document.body.textContent?.includes("No shared notes yet"));
  assert(!document.querySelector('[role="switch"]') && !button("Erase memories"), "Editor has admin controls");
  status = { ...status, status: "unavailable" }; mount("admin", "unavailable");
  await until(() => document.body.textContent?.includes("Analysis is not configured"));
  assert(switchFor("analysis").disabled, "Unavailable analysis is editable");
  document.querySelector("details")!.open = true;
  button("Erase memories")!.click(); await until(() => document.querySelector("[data-confirm]"));
  assert(purges === 0, "Erased without confirmation");
  (document.querySelector("[data-confirm]") as HTMLButtonElement).click();
  await until(() => Number(purges) === 1 && !document.querySelector('[role="dialog"]'));
  status = { ...status, status: "deleting" }; mount("admin", "deleting");
  await until(() => document.body.textContent?.includes("Deleting memories"));
  assert(switchFor("analysis").disabled && button("Erase memories")!.disabled, "Deleting state allows conflicting writes");
  statusFail = true; mount("admin", "read-error");
  await until(() => button("Reload status"));
  assert(switchFor("analysis").disabled, "Unknown state allows writes");
  statusFail = false; button("Reload status")!.click();
  await until(() => !button("Reload status"));
  status = { ...status, status: "indexing", enabled: true };
  enabledWorkspace = "";
  mount("viewer", "compact", true);
  await until(() => enabledWorkspace === "team" && !document.querySelector("h2"));
  assert(!document.querySelector('[role="switch"]') && !button("Show shared notes"), "Settings leaked into compact chat");
  assert(!document.querySelector('[role="status"]'), "Background memory progress leaked into chat");
  root.render(<SaveSharedMemory key="no-model" workspaceId="team" workspaceName="Team" content="Answer to share" question="Question" model="" />);
  await until(() => button("Share to memory")); button("Share to memory")!.click();
  await until(() => document.querySelector('[role="dialog"] textarea'));
  assert(!button("Generate memory draft"), "Draft generation is available without a selected model");
  assert(document.querySelector<HTMLTextAreaElement>('textarea')!.disabled === false, "Missing model blocks manual editing");
  (document.querySelector("[data-confirm]") as HTMLButtonElement).click();
  await until(() => sharedContent === "Answer to share" && !document.querySelector('[role="dialog"]'));
  root.render(<SaveSharedMemory key="with-model" workspaceId="team" workspaceName="Team" content="Answer to share" question="Question" model="model" />);
  await until(() => button("Share to memory") && !button("Share to memory")!.disabled); button("Share to memory")!.click();
  await until(() => button("Generate memory draft"));
  (document.querySelector("[data-cancel]") as HTMLButtonElement).click();
  await until(() => !document.querySelector('[role="dialog"]'));
  document.getElementById("result")!.textContent = "PASS: model availability and manual sharing, error recovery, confirmation, notes failure/retry/empty, viewer/editor boundaries, unavailable purge, deleting, compact";
}
void run().catch((error: unknown) => { document.getElementById("result")!.textContent = `FAIL: ${String(error)}`; });
