import { execFileSync } from "node:child_process";
import { createRequire } from "node:module";
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { dirname, resolve, join } from "node:path";
import assert from "node:assert/strict";

const require = createRequire(import.meta.url);
const root = resolve(import.meta.dirname, "..");
const output = resolve(root, "../desktop/Sources/Dahlia/Resources/Documents");
execFileSync(process.execPath, [require.resolve("tsup/dist/cli-default.js"), "--config", "tsup.documents.config.ts"], { cwd: root, stdio: "inherit" });
const metadata = JSON.parse(readFileSync(join(root, "dist/documents/metafile-iife.json"), "utf8"));
const packages = new Map();
for (const input of Object.keys(metadata.inputs).filter((name) => name.includes("node_modules/"))) {
  let folder = dirname(resolve(root, input));
  while (!existsSync(join(folder, "package.json"))) {
    assert.notEqual(folder, dirname(folder), `Package missing for ${input}`);
    folder = dirname(folder);
  }
  const pkg = JSON.parse(readFileSync(join(folder, "package.json"), "utf8"));
  const licenses = readdirSync(folder).filter((name) => /^licen[cs]e(?:\.|$)/i.test(name));
  assert(licenses.length > 0, `Bundled dependency ${pkg.name} has no license file`);
  packages.set(`${pkg.name}@${pkg.version}`, licenses.sort().map((name) => readFileSync(join(folder, name), "utf8").trim()).join("\n\n"));
}
const files = new Map(["document-core.global.js", "document-editor.global.js"].map((name) => [name, readFileSync(join(root, "dist/documents", name), "utf8")]));
files.set("document-editor.css", readFileSync(join(root, "src/documents/editor.css"), "utf8"));
files.set("DOCUMENT-LICENSES.txt", "Bundled Documents dependencies (generated by pnpm documents:build)\n\n" + [...packages].sort(([a], [b]) => a.localeCompare(b, "en")).map(([name, license]) => `${name}\n${"=".repeat(name.length)}\n${license}\n`).join("\n"));
for (const [name, body] of files) {
  const path = join(output, name);
  if (process.argv.includes("--check")) assert.equal(readFileSync(path, "utf8"), body, `${name} is stale; run pnpm documents:build`);
  else writeFileSync(path, body);
}
console.log(`Verified ${files.size} Desktop resources and ${packages.size} bundled dependency licenses.`);
